### ISSUE TITLE
[FEATURE] Redesign the (PsychoJS) hello and goodbye screens

### ISSUE THREAD

**Issue by denispelli** [EasyEyes/threshold#18]
**Is your feature request related to a problem? Please describe.**
**What's easily changed?** 
Show our logo!
Please clean up the request for participant name. It should say "Welcome to EasyEyes Threshold."

The Hello and Goodbye screens are ugly.
**Describe the solution you'd like**
**When I aborted by hitting Escape it says "Thank you for your patience."
Please change "patience" to "participation."**

**Additional context**

**Comment by peilingjiang** [comment]
Hi @denispelli, it's possible.

It's easy to: change the styles of the buttons and header, etc. Modify the text.
It's hard to: Add a new button.

Another thing is that in order to do this, we need to use a customized (forked) version of PsychoJS (just like Calibrator is using a customized version of WebGazer). It's not a huge workload, just a note for changes.

**Comment by denispelli** [comment]
Dear Peiling
Oh! 
Let's not fork PsychoJS until we have a more substantial reason to do so. I don't want to create a delay in passing through the latest release of PsychoJS, which they seem to update twice a year, January and June, plus unexpected bug fixes.

Within what's possible, please update the text:
1. In the splash screen, please remove "Fields marked with an asterisk (*) are required." Can we hide it by drawing a blank rectangle over it?
2. In the splash screen, replace "Threshold" by "Welcome to EasyEyes Threshold."
3. When I aborted by hitting Escape, it says "Thank you for your patience." There, and any other place that phrase occurs, please change "patience" to "participation."

Can we do that?
