### ISSUE TITLE
[FEATURE] Plan how EasyEyes web page will control Pavlovia

### ISSUE THREAD

**Issue by peilingjiang** [EasyEyes/threshold#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by svr8** [comment]
This is an update on requirements:
1. The data collected by the scientist will be private.
2. The experiment code uploaded by repository can be public/private.

We want scientists to register on EasyEyes website and easily generate a URL for their experiment, that is hosted by Pavlovia.

### Possible Scenario
1. Scientists register/sign in on EasyEyes using Gitlab OAuth. 
2. EasyEyes creates their profile in a separate database. This will be later used to record payments for individual scientist.
3. EasyEyes allows them to upload an experiment.
4. Pavlovia is used to make the experiment live.

### TODO
1. [ ] Check if it is possible to create a private/publlic repository on behalf of scientist on Pavlovia.
2. [ ] Check if it is possible to run an experiment with a private repository.

**Comment by svr8** [comment]
@sagarrpandav Can you review this flow once?

**Comment by denispelli** [comment]
The next step is to create code that uses OAuth to log into Pavlovia, creates a new project there, and uploads files.

**Comment by svr8** [comment]
There some more updates by denis:
* A scientist registers/signs in to EasyEyes. 
* EasyEyes creates/updates their profile in an EasyEyes user database. This will save the OAuth key for Pavlovia, and track the number of participants tested, to later bill the scientist.
* EasyEyes uses Gitlab OAuth to log into the scientist's Pavlovia account.
* EasyEyes allows the scientist to upload any number of fonts. The fonts are uploaded to a (possibly new) Fonts folder in the scientist's Pavlovia account. Note that this Fonts folder should accumulate all the fonts the scientist ever uploaded. It's not specific to a particular experiment. (Do we need to provide a way to delete a file from that folder?) Scientists will want to see a text directory of their Fonts folder, to see which fonts are there, and to get the exact name. They should be able to select and copy that text.
* EasyEyes allows the scientist to upload one experiment table.
* The EasyEyes preprocessor converts the scientist's table to a "blocks" folder of smaller tables, as explained in the manual. References to uploaded fonts will be converted to URLs pointing to the scientist's Pavlovia Fonts folder. The URLs will ultimately be used in the javascript FontFace command, either in threshold.js, or, eventually, in PsychoJS.js.
* EasyEyes uploads the files needed to run the experiment: the blocks folder, index.html, threshold.js, and PsychoJS.js. 
* EasyEyes returns a URL. Loading that URL runs the experiment. The URL points to the scientist's new folder in their Pavlovia account. Pavlovia is a server intended for heavy use.

**More update about above**
The scientist uploads a table to easyeyes.  The Preprocessor runs locally on easyeyes. This is important because the scientist needs feedback on errors immediately, not hours later.

**Comment by sagarrpandav** [comment]
Updating a possible way to verify the relation between Easy Eyes Users DB and linked Palvolia Gitlab
Accounts if and when we do


Whats Needed :

In order to maintain a consistent db which links Easy Eyes Users with that of Palvolia Gitlab,
we need some kind of mechanism to confirm that the user is authorized and can access the gitlab
account mentioned. For this, we can use the private key which scientist can generate with a short life
for the purpose of verification.

How will we verify:

Once user visits Easy Eyes Threshold Page, she/he will be prompted to login via Google.
Once Google authorizes the user, we will check whether scientist is registered on Easy Eyes via a REST Call.
If no, we will use the data received from Google (Name & Email) and add to the db.
Now, to verify the scientist's gitlab account, we will ask for the gitlab username and a private key.
Once we get these 2 parameters, we will encrypt these 2 fields, and send to the server.
Server will decrypt and extract them, and make exactly 4 REST calls to the GITLAB Exposed APIS
1. Get Status - will return current status of scientist's account
2. Set Status - we will set some OTP
3. Get Status - we will read the status, and verify OTP matches. If yes, verification is done.
4. Set Status - we will reset the status to the scientist's original status

Now, that we will ensure consistent data in our own database, we can build ahead and integrate 
other read/write richer functionalities.

**Comment by denispelli** [comment]
Dear Sagar and Shikhar
Thanks for writing out the plan. However, it's too complicated. I wrote out a simpler plan in the Web sheet of the Manual:
https://docs.google.com/spreadsheets/d/1x65NjykMm-XUOz98Eu_oo6ON2xspm_h0Q0M2u6UGtug/edit#gid=1385703808

EasyEyes will have NO DATABASE of scientists or anyone else. It will NOT keep track of the scientists. It will get the scientist to log into their Pavlovia account, and will use that account. Once the Pavlovia account is open, EasyEyes uses it. If not, it can't. There is no need to "verify" the scientist. The only thing that EasyEyes might save, if the scientist gives permission, is their Pavlovia credentials as a cookie on the **scientist's** computer.  The cookie allows the scientist to come back at a future date and get to work again without having to log into Pavlovia. EasyEyes saves nothing locally, except that it temporarily creates a blocks folder with numbered block files in it, that it uploads to Pavlovia. Once uploaded, the local copy is deleted. Ok?

This is urgent. The EasyEyes/threshold web page needs to **upload** fonts, consent forms, and experiment files to the scientist's Pavlovia account. **Can you provide Javascript code to do this ASAP?** We need this capability immediately.

Best
Denis
