### ISSUE TITLE
[BUG] Error `Cannot find readingFirstFewwords in the given corpus` is seen while running a new experiment table

### ISSUE THREAD

**Issue by sravyam28** [EasyEyes/threshold#82]
**Describe the bug**

 Error `Cannot find readingFirstFewwords in the given corpus` is seen while running a new experiment table

**To Reproduce**

Add the below table to examples folder. 
Run `npm run examples`
run `npm start -- --name=easyeyes_buggy`

[easyeyes_buggy.csv](https://github.com/EasyEyes/threshold/files/15474273/easyeyes_buggy.csv)

**Expected behavior**

To run experiment without any errors

**Screenshots**

![441289594_1125558158711799_7381044262460196188_n (1)](https://github.com/EasyEyes/threshold/assets/117389237/76d77188-1fed-423c-bc30-18dd461a4a74)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by minjungkim85** [comment]
To be clear, this bug report is also from me. Thank you! @denispelli @aburchell

**Comment by denispelli** [comment]
Hi. I hope this has been fixed. I was experiencing a different symptom of
proceeding without error message, but with text from the wrong place in the
corpus. That was fixed so the reading text stimulus now starts at the right
place in the corpus, specified by the few words. I’m hoping your false
alarm error is fixed too.

There are three cases to consider.

   1. When the desired words ARE in the corpus then the reading should
   start there. I think EasyEyes now delivers that.
   2. When the desired words are NOT in the corpus, I think EasyEyes
   currently gives a runtime error, like what you reported, though that was a
   false alarm.
   3. I have requested, but I don’t think is yet implemented, that EasyEyes
   also look for the desired words at COMPILE time, and generate a fatal
   compile error if not found. In that case the runtime error would never
   happen. Compile-time errors are much more convenient than runtime errors,
   quickly fixed with no wasted time of scientist or participants.

Best
Denis
