### ISSUE TITLE
[BUG]the output font does not match the font specified in the table

### ISSUE THREAD

**Issue by sravyam28** [EasyEyes/threshold#86]
**Describe the bug**

the output font does not match the font specified in the table

**To Reproduce**

add the below table to tables folder and run using npm start
[SGSampleTable.csv](https://github.com/user-attachments/files/16565365/SGSampleTable.csv)

**Expected behavior**

the font on the experiment should be the one specified in the table

**Screenshots**
![output font](https://github.com/user-attachments/assets/b31cdb30-d316-4490-ab65-81fc5dc5dec8)

**Desktop (please complete the following information):**

- OS: MAC

**Comment by denispelli** [comment]
Using a website to identify the font, it seems to be Times New Roman, which is very different from Optimistic, confirming the bug report. 

We have mostly used fonts in woff2 format, so that is the most tested case. EasyEyes should support the ttf format too, but it has been tested very little.
Optimistic_Text_Rg.ttf
Roboto Mono.woff2

When submitting bug reports, it's ideal to share a an export.zip archive. Once you've compiled your experiment in EasyEyes, click the "Export" button. This zip includes the spreadsheet and any required resources. In this case, it would include the Optimistic and Roboto Mono font files. Providing an export.zip archive is a big help to the programmer trying to work on the bug.

Sourcing Roboto Mono from a file is fine. You can also get it from Google Fonts by setting instructionFontSource "google".

**Comment by denispelli** [comment]
Now resolved. See email to MJ and [sravyam28](https://github.com/sravyam28) August 21, 2024.
